### ISSUE TITLE
Can I ask for this template to be updated to bring it inline with the latest create-t3-turbo?

### ISSUE THREAD

**Issue by shawnlikescode** [clerk/t3-turbo-and-clerk#93]
Latest create-t3-turbo has some pretty significant changes is there any intention to update this template?

**Comment by JacobMGEvans** [comment]
Yeah, I will follow up with the readiness of this repo. Thanks for issue 😄

**Comment by frednomoon** [comment]
Any update on this? :)

**Comment by JacobMGEvans** [comment]
It is planned for Q1 and we will get to it soon. Appreciate your patience.

**Comment by JacobMGEvans** [comment]
https://github.com/clerk/t3-turbo-and-clerk/issues/94
